pipeline {
    agent any
    tools {
      maven "maven-nodo-principal"
    }
    stages {
        stage('Build') {
            steps {
                dir('jenkins/ejercicios/cicd/infra-ii') {
                    sh 'mvn -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
      success {
            dir (‘maven-adderapp’) {
            archiveArtifacts artifacts: 'target/*.jar', fingerprint:
            true
                                   }
              }
          }
}
